// Complete Server-side Student Data Helper for Deeksharambh System

export const b3FullStudents = [
  { _id: 'std_7_1', sNo: 1, rollNo: '26CS01', registerNo: '26101', name: "AAYISHA SIDHIKA D", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_7_2', sNo: 2, rollNo: '26CS02', registerNo: '26102', name: "AGASTIAN G E", mathsStream: "HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_7_3', sNo: 3, rollNo: '26CS03', registerNo: '26103', name: "BALAJI I", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_7_4', sNo: 4, rollNo: '26CS04', registerNo: '26104', name: "DHANASRI A", mathsStream: "HSC", attendancePercentage: 97, category: 'Advanced Learner' },
  { _id: 'std_7_5', sNo: 5, rollNo: '26CS05', registerNo: '26105', name: "DHARUNKUMAR V", mathsStream: "NON_HSC", attendancePercentage: 85, category: 'Slow Learner' },
  { _id: 'std_7_6', sNo: 6, rollNo: '26CS06', registerNo: '26106', name: "DINEESH KUMAR J", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_7_7', sNo: 7, rollNo: '26CS07', registerNo: '26107', name: "DIVYADHARSHINI A", mathsStream: "HSC", attendancePercentage: 98, category: 'Advanced Learner' },
  { _id: 'std_7_8', sNo: 8, rollNo: '26CS08', registerNo: '26108', name: "DURGA SRI S", mathsStream: "NON_HSC", attendancePercentage: 83, category: 'Slow Learner' },
  { _id: 'std_7_9', sNo: 9, rollNo: '26CS09', registerNo: '26109', name: "GOBIKA C R", mathsStream: "NON_HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_7_10', sNo: 10, rollNo: '26CS10', registerNo: '26110', name: "HARIHARASUDHAN M", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_7_11', sNo: 11, rollNo: '26CS11', registerNo: '26111', name: "HARITHA B", mathsStream: "HSC", attendancePercentage: 90, category: 'Advanced Learner' },
  { _id: 'std_7_12', sNo: 12, rollNo: '26CS12', registerNo: '26112', name: "HARIVARATHAN A", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_7_13', sNo: 13, rollNo: '26CS13', registerNo: '26113', name: "ILLAKIYA R", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_7_14', sNo: 14, rollNo: '26CS14', registerNo: '26114', name: "JAYSHREE S", mathsStream: "NON_HSC", attendancePercentage: 87, category: 'Average' },
  { _id: 'std_7_15', sNo: 15, rollNo: '26CS15', registerNo: '26115', name: "KARUPPUSAMY S", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_7_16', sNo: 16, rollNo: '26CS16', registerNo: '26116', name: "KAVIYA R", mathsStream: "NON_HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_7_17', sNo: 17, rollNo: '26CS17', registerNo: '26117', name: "KEERTHANA C", mathsStream: "HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_7_18', sNo: 18, rollNo: '26CS18', registerNo: '26118', name: "LAKSHITHA MAYUGA KUMARI M", mathsStream: "NON_HSC", attendancePercentage: 86, category: 'Average' },
  { _id: 'std_7_19', sNo: 19, rollNo: '26CS19', registerNo: '26119', name: "LAVANYA K", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_7_20', sNo: 20, rollNo: '26CS20', registerNo: '26120', name: "MADHUMATHI R", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_7_21', sNo: 21, rollNo: '26CS21', registerNo: '26121', name: "MEGA SRI B", mathsStream: "NON_HSC", attendancePercentage: 84, category: 'Slow Learner' },
  { _id: 'std_7_22', sNo: 22, rollNo: '26CS22', registerNo: '26122', name: "NAVANEETHAKRISHNAN S", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_7_23', sNo: 23, rollNo: '26CS23', registerNo: '26123', name: "NAVEEN M", mathsStream: "HSC", attendancePercentage: 90, category: 'Advanced Learner' },
  { _id: 'std_7_24', sNo: 24, rollNo: '26CS24', registerNo: '26124', name: "NIGHILA S V", mathsStream: "HSC", attendancePercentage: 97, category: 'Advanced Learner' },
  { _id: 'std_7_25', sNo: 25, rollNo: '26CS25', registerNo: '26125', name: "NITHINRAJ S", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_7_26', sNo: 26, rollNo: '26CS26', registerNo: '26126', name: "NITHISH M", mathsStream: "HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_7_27', sNo: 27, rollNo: '26CS27', registerNo: '26127', name: "NITHYA SREE G", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_7_28', sNo: 28, rollNo: '26CS28', registerNo: '26128', name: "OMESHWAR S", mathsStream: "HSC", attendancePercentage: 91, category: 'Advanced Learner' },
  { _id: 'std_7_29', sNo: 29, rollNo: '26CS29', registerNo: '26129', name: "PANDISELVI P", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_7_30', sNo: 30, rollNo: '26CS30', registerNo: '26130', name: "PRADHEEPA DEVI B", mathsStream: "HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_7_31', sNo: 31, rollNo: '26CS31', registerNo: '26131', name: "PRAMADEESH S", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_7_32', sNo: 32, rollNo: '26CS32', registerNo: '26132', name: "RATHNA S", mathsStream: "HSC", attendancePercentage: 98, category: 'Advanced Learner' },
  { _id: 'std_7_33', sNo: 33, rollNo: '26CS33', registerNo: '26133', name: "RITHICK A", mathsStream: "HSC", attendancePercentage: 91, category: 'Advanced Learner' },
  { _id: 'std_7_34', sNo: 34, rollNo: '26CS34', registerNo: '26134', name: "ROBERT JONES P", mathsStream: "NON_HSC", attendancePercentage: 86, category: 'Average' },
  { _id: 'std_7_35', sNo: 35, rollNo: '26CS35', registerNo: '26135', name: "SANJEEVKUMAR R", mathsStream: "HSC", attendancePercentage: 90, category: 'Advanced Learner' },
  { _id: 'std_7_36', sNo: 36, rollNo: '26CS36', registerNo: '26136', name: "SANTHOSH K", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_7_37', sNo: 37, rollNo: '26CS37', registerNo: '26137', name: "SATHEESH P", mathsStream: "NON_HSC", attendancePercentage: 85, category: 'Slow Learner' },
  { _id: 'std_7_38', sNo: 38, rollNo: '26CS38', registerNo: '26138', name: "SIVARAMAKRISHNAN M", mathsStream: "NON_HSC", attendancePercentage: 87, category: 'Average' },
  { _id: 'std_7_39', sNo: 39, rollNo: '26CS39', registerNo: '26139', name: "THARUN V", mathsStream: "HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_7_40', sNo: 40, rollNo: '26CS40', registerNo: '26140', name: "VAISHNAVI S", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_7_41', sNo: 41, rollNo: '26CS41', registerNo: '26141', name: "VARSHINI R", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_7_42', sNo: 42, rollNo: '26CS42', registerNo: '26142', name: "VIPIN KRISHNA P", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_7_43', sNo: 43, rollNo: '26CS43', registerNo: '26143', name: "VISHNU R", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_7_44', sNo: 44, rollNo: '26CS44', registerNo: '26144', name: "YOGESHWARAN R", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_7_45', sNo: 45, rollNo: '26CS45', registerNo: '26145', name: "EBINESH V", mathsStream: "NON_HSC", attendancePercentage: 84, category: 'Slow Learner' }
];

export const b2FullStudents = [
  { _id: 'std_6_1', sNo: 1, rollNo: '25CS01', registerNo: '25101', name: "Saarah Azizah K.M", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_6_2', sNo: 2, rollNo: '25CS02', registerNo: '25102', name: "Mahadharshini V", mathsStream: "NON_HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_6_3', sNo: 3, rollNo: '25CS03', registerNo: '25103', name: "Kaavya P", mathsStream: "HSC", attendancePercentage: 97, category: 'Advanced Learner' },
  { _id: 'std_6_4', sNo: 4, rollNo: '25CS04', registerNo: '25104', name: "Karthikaa P", mathsStream: "HSC", attendancePercentage: 98, category: 'Advanced Learner' },
  { _id: 'std_6_5', sNo: 5, rollNo: '25CS05', registerNo: '25105', name: "Abarna C", mathsStream: "NON_HSC", attendancePercentage: 84, category: 'Slow Learner' },
  { _id: 'std_6_6', sNo: 6, rollNo: '25CS06', registerNo: '25106', name: "Subiskha . P", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_6_7', sNo: 7, rollNo: '25CS07', registerNo: '25107', name: "Neha Sai .S", mathsStream: "HSC", attendancePercentage: 96, category: 'Average' },
  { _id: 'std_6_8', sNo: 8, rollNo: '25CS08', registerNo: '25108', name: "Varshini M", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Advanced Learner' },
  { _id: 'std_6_9', sNo: 9, rollNo: '25CS09', registerNo: '25109', name: "Abhinaya M", mathsStream: "HSC", attendancePercentage: 94, category: 'Slow Learner' },
  { _id: 'std_6_10', sNo: 10, rollNo: '25CS10', registerNo: '25110', name: "Shandhanalakshmi C", mathsStream: "HSC", attendancePercentage: 99, category: 'Advanced Learner' },
  { _id: 'std_6_11', sNo: 11, rollNo: '25CS11', registerNo: '25111', name: "Gowri P", mathsStream: "NON_HSC", attendancePercentage: 90, category: 'Advanced Learner' },
  { _id: 'std_6_12', sNo: 12, rollNo: '25CS12', registerNo: '25112', name: "Janaka Nandhini M", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_6_13', sNo: 13, rollNo: '25CS13', registerNo: '25113', name: "Indhumathi N", mathsStream: "NON_HSC", attendancePercentage: 91, category: 'Advanced Learner' },
  { _id: 'std_6_14', sNo: 14, rollNo: '25CS14', registerNo: '25114', name: "Dharaneesh P.B", mathsStream: "HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_6_15', sNo: 15, rollNo: '25CS15', registerNo: '25115', name: "Madhan Prasanth A", mathsStream: "NON_HSC", attendancePercentage: 82, category: 'Slow Learner' },
  { _id: 'std_6_16', sNo: 16, rollNo: '25CS16', registerNo: '25116', name: "Sanjay Aravind .R", mathsStream: "NON_HSC", attendancePercentage: 85, category: 'Average' },
  { _id: 'std_6_17', sNo: 17, rollNo: '25CS17', registerNo: '25117', name: "Keshav balaji K", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_6_18', sNo: 18, rollNo: '25CS18', registerNo: '25118', name: "Sharmila M", mathsStream: "HSC", attendancePercentage: 97, category: 'Advanced Learner' },
  { _id: 'std_6_19', sNo: 19, rollNo: '25CS19', registerNo: '25119', name: "Surya G", mathsStream: "NON_HSC", attendancePercentage: 86, category: 'Average' },
  { _id: 'std_6_20', sNo: 20, rollNo: '25CS20', registerNo: '25120', name: "Vijay C", mathsStream: "HSC", attendancePercentage: 80, category: 'Slow Learner' },
  { _id: 'std_6_21', sNo: 21, rollNo: '25CS21', registerNo: '25121', name: "Kalaiyarasan A", mathsStream: "NON_HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_6_22', sNo: 22, rollNo: '25CS22', registerNo: '25122', name: "Arthi B", mathsStream: "HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_6_23', sNo: 23, rollNo: '25CS23', registerNo: '25123', name: "Kaviya Lakshmi M", mathsStream: "NON_HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_6_24', sNo: 24, rollNo: '25CS24', registerNo: '25124', name: "Ramanujam P", mathsStream: "HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_6_25', sNo: 25, rollNo: '25CS25', registerNo: '25125', name: "Shameer S", mathsStream: "NON_HSC", attendancePercentage: 81, category: 'Slow Learner' },
  { _id: 'std_6_26', sNo: 26, rollNo: '25CS26', registerNo: '25126', name: "Prakash S", mathsStream: "NON_HSC", attendancePercentage: 83, category: 'Slow Learner' },
  { _id: 'std_6_27', sNo: 27, rollNo: '25CS27', registerNo: '25127', name: "Kiruthik C", mathsStream: "HSC", attendancePercentage: 90, category: 'Average' },
  { _id: 'std_6_28', sNo: 28, rollNo: '25CS28', registerNo: '25128', name: "Ajay M", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_6_29', sNo: 29, rollNo: '25CS29', registerNo: '25129', name: "Illakiya R", mathsStream: "NON_HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_6_30', sNo: 30, rollNo: '25CS30', registerNo: '25130', name: "Sandhiya S", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_6_31', sNo: 31, rollNo: '25CS31', registerNo: '25131', name: "Keerthana V", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_6_32', sNo: 32, rollNo: '25CS32', registerNo: '25132', name: "Gokulraj P", mathsStream: "HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_6_33', sNo: 33, rollNo: '25CS33', registerNo: '25133', name: "Sunil Kumar M", mathsStream: "HSC", attendancePercentage: 87, category: 'Average' },
  { _id: 'std_6_34', sNo: 34, rollNo: '25CS34', registerNo: '25134', name: "Naveen V", mathsStream: "NON_HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_6_35', sNo: 35, rollNo: '25CS35', registerNo: '25135', name: "Dhanaseelan R M", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_6_36', sNo: 36, rollNo: '25CS36', registerNo: '25136', name: "Bharathraj R", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_6_37', sNo: 37, rollNo: '25CS37', registerNo: '25137', name: "Pooja", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_6_38', sNo: 38, rollNo: '25CS38', registerNo: '25138', name: "Niroshini R", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_6_39', sNo: 39, rollNo: '25CS39', registerNo: '25139', name: "Sri ruthra", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_6_40', sNo: 40, rollNo: '25CS40', registerNo: '25140', name: "Sasiram S", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_6_41', sNo: 41, rollNo: '25CS41', registerNo: '25141', name: "Harani", mathsStream: "NON_HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_6_42', sNo: 42, rollNo: '25CS42', registerNo: '25142', name: "Thirumurugam.M", mathsStream: "HSC", attendancePercentage: 86, category: 'Average' },
  { _id: 'std_6_43', sNo: 43, rollNo: '25CS43', registerNo: '25143', name: "Sathendrareddy", mathsStream: "NON_HSC", attendancePercentage: 95, category: 'Advanced Learner' }
];

export const b1FullStudents = [
  { _id: 'std_5_1', sNo: 1, rollNo: '24CS01', registerNo: '24101', name: "ABINESH.M", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_5_2', sNo: 2, rollNo: '24CS02', registerNo: '24102', name: "ABISHEK.S", mathsStream: "NON_HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_5_3', sNo: 3, rollNo: '24CS03', registerNo: '24103', name: "ANGELIN GIFTY.I", mathsStream: "HSC", attendancePercentage: 98, category: 'Advanced Learner' },
  { _id: 'std_5_4', sNo: 4, rollNo: '24CS04', registerNo: '24104', name: "ARTHI.M", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_5_5', sNo: 5, rollNo: '24CS05', registerNo: '24105', name: "ASWINI.S", mathsStream: "NON_HSC", attendancePercentage: 86, category: 'Slow Learner' },
  { _id: 'std_5_6', sNo: 6, rollNo: '24CS06', registerNo: '24106', name: "DEVI PRIYA.M", mathsStream: "HSC", attendancePercentage: 92, category: 'Average' },
  { _id: 'std_5_7', sNo: 7, rollNo: '24CS07', registerNo: '24107', name: "DHANABAL.L", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_5_8', sNo: 8, rollNo: '24CS08', registerNo: '24108', name: "DHANUSH.S", mathsStream: "HSC", attendancePercentage: 90, category: 'Advanced Learner' },
  { _id: 'std_5_9', sNo: 9, rollNo: '24CS09', registerNo: '24109', name: "DHANYA.D", mathsStream: "NON_HSC", attendancePercentage: 83, category: 'Slow Learner' },
  { _id: 'std_5_10', sNo: 10, rollNo: '24CS10', registerNo: '24110', name: "DHARANI.S", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_5_11', sNo: 11, rollNo: '24CS11', registerNo: '24111', name: "DHARUNESH.S", mathsStream: "NON_HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_5_12', sNo: 12, rollNo: '24CS12', registerNo: '24112', name: "DINESH KARTHIK.S", mathsStream: "NON_HSC", attendancePercentage: 85, category: 'Average' },
  { _id: 'std_5_13', sNo: 13, rollNo: '24CS13', registerNo: '24113', name: "GOKUL.K", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_5_14', sNo: 14, rollNo: '24CS14', registerNo: '24114', name: "GOKULAKRISHNAN.K", mathsStream: "HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_5_15', sNo: 15, rollNo: '24CS15', registerNo: '24115', name: "GOWRIKRISHNA.N.S", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_5_16', sNo: 16, rollNo: '24CS16', registerNo: '24116', name: "HARIHARAN.S", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_5_17', sNo: 17, rollNo: '24CS17', registerNo: '24117', name: "HEMALATHA.M", mathsStream: "HSC", attendancePercentage: 86, category: 'Slow Learner' },
  { _id: 'std_5_18', sNo: 18, rollNo: '24CS18', registerNo: '24118', name: "HEMAMALINI.R", mathsStream: "HSC", attendancePercentage: 90, category: 'Average' },
  { _id: 'std_5_19', sNo: 19, rollNo: '24CS19', registerNo: '24119', name: "JAYASURYA.R", mathsStream: "HSC", attendancePercentage: 91, category: 'Average' },
  { _id: 'std_5_20', sNo: 20, rollNo: '24CS20', registerNo: '24120', name: "JEFFRINA.V", mathsStream: "HSC", attendancePercentage: 99, category: 'Advanced Learner' },
  { _id: 'std_5_21', sNo: 21, rollNo: '24CS21', registerNo: '24121', name: "JINOJ.M", mathsStream: "HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_5_22', sNo: 22, rollNo: '24CS22', registerNo: '24122', name: "KAMALESH.P", mathsStream: "HSC", attendancePercentage: 87, category: 'Average' },
  { _id: 'std_5_23', sNo: 23, rollNo: '24CS23', registerNo: '24123', name: "KANGAR BHARATHESWARAN.M", mathsStream: "NON_HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_5_24', sNo: 24, rollNo: '24CS24', registerNo: '24124', name: "KASTHURI KAVIYA.S", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_5_25', sNo: 25, rollNo: '24CS25', registerNo: '24125', name: "KOWSALYA.M", mathsStream: "HSC", attendancePercentage: 84, category: 'Slow Learner' },
  { _id: 'std_5_26', sNo: 26, rollNo: '24CS26', registerNo: '24126', name: "LAVANYA KUMAR.S", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_5_27', sNo: 27, rollNo: '24CS27', registerNo: '24127', name: "MAKIZH.N", mathsStream: "HSC", attendancePercentage: 96, category: 'Advanced Learner' },
  { _id: 'std_5_28', sNo: 28, rollNo: '24CS28', registerNo: '24128', name: "MIRUDHULASINI.R", mathsStream: "HSC", attendancePercentage: 97, category: 'Advanced Learner' },
  { _id: 'std_5_29', sNo: 29, rollNo: '24CS29', registerNo: '24129', name: "MURUGAPRIYA.I", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_5_30', sNo: 30, rollNo: '24CS30', registerNo: '24130', name: "NIRANJAN.A", mathsStream: "HSC", attendancePercentage: 91, category: 'Advanced Learner' },
  { _id: 'std_5_31', sNo: 31, rollNo: '24CS31', registerNo: '24131', name: "NISHAANTH.D", mathsStream: "NON_HSC", attendancePercentage: 86, category: 'Average' },
  { _id: 'std_5_32', sNo: 32, rollNo: '24CS32', registerNo: '24132', name: "PAVITHRA.M", mathsStream: "HSC", attendancePercentage: 90, category: 'Average' },
  { _id: 'std_5_33', sNo: 33, rollNo: '24CS33', registerNo: '24133', name: "PRABU.S", mathsStream: "HSC", attendancePercentage: 85, category: 'Average' },
  { _id: 'std_5_34', sNo: 34, rollNo: '24CS34', registerNo: '24134', name: "PRAVEEN. N H", mathsStream: "NON_HSC", attendancePercentage: 82, category: 'Slow Learner' },
  { _id: 'std_5_35', sNo: 35, rollNo: '24CS35', registerNo: '24135', name: "PRAVEEN RAJA.G", mathsStream: "NON_HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_5_36', sNo: 36, rollNo: '24CS36', registerNo: '24136', name: "PRIYANKA.S", mathsStream: "HSC", attendancePercentage: 95, category: 'Advanced Learner' },
  { _id: 'std_5_37', sNo: 37, rollNo: '24CS37', registerNo: '24137', name: "RITHIKA.R", mathsStream: "HSC", attendancePercentage: 92, category: 'Advanced Learner' },
  { _id: 'std_5_38', sNo: 38, rollNo: '24CS38', registerNo: '24138', name: "ROHITH.P", mathsStream: "HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_5_39', sNo: 39, rollNo: '24CS39', registerNo: '24139', name: "SACHIN .S", mathsStream: "NON_HSC", attendancePercentage: 90, category: 'Average' },
  { _id: 'std_5_40', sNo: 40, rollNo: '24CS40', registerNo: '24140', name: "SATHIYA.V", mathsStream: "HSC", attendancePercentage: 87, category: 'Average' },
  { _id: 'std_5_41', sNo: 41, rollNo: '24CS41', registerNo: '24141', name: "SIVA.S", mathsStream: "HSC", attendancePercentage: 91, category: 'Advanced Learner' },
  { _id: 'std_5_42', sNo: 42, rollNo: '24CS42', registerNo: '24142', name: "SRIVARTHINI.V", mathsStream: "HSC", attendancePercentage: 93, category: 'Advanced Learner' },
  { _id: 'std_5_43', sNo: 43, rollNo: '24CS43', registerNo: '24143', name: "STEPHEN THAYANITHI.J", mathsStream: "HSC", attendancePercentage: 89, category: 'Average' },
  { _id: 'std_5_44', sNo: 44, rollNo: '24CS44', registerNo: '24144', name: "SUKESH.A R", mathsStream: "NON_HSC", attendancePercentage: 94, category: 'Advanced Learner' },
  { _id: 'std_5_45', sNo: 45, rollNo: '24CS45', registerNo: '24145', name: "TAMILARASAN.S", mathsStream: "HSC", attendancePercentage: 83, category: 'Slow Learner' },
  { _id: 'std_5_46', sNo: 46, rollNo: '24CS46', registerNo: '24146', name: "THENMOZHI.M", mathsStream: "HSC", attendancePercentage: 88, category: 'Average' },
  { _id: 'std_5_47', sNo: 47, rollNo: '24CS47', registerNo: '24147', name: "VENGATESHWARAN.N", mathsStream: "HSC", attendancePercentage: 89, category: 'Average' }
];

export function getFullBatchStudents(batchIdOrObj) {
  const ver = (batchIdOrObj?.deeksharambhVersion || batchIdOrObj?.batchYearRange || batchIdOrObj || '').toString();
  if (ver.includes('5.0') || ver.includes('2024')) {
    return b1FullStudents;
  }
  if (ver.includes('6.0') || ver.includes('2025')) {
    return b2FullStudents;
  }
  return b3FullStudents;
}
